### ISSUE TITLE
fix(load): Can't load with QuickShop-Hikari

### ISSUE THREAD

**Issue by Trcmoe** [ArtformGames/UserSuffix#7]
### **Description**

我试着在服务器中使用这个插件，但是发现插件无法使用。

### **Screenshots & Error Logs**
```
[19:09:12 INFO]: [UserSuffix] Enabling UserSuffix v1.3.1
[19:09:12 INFO]: [UserSuffix]  _   _             ___       __  __ _
[19:09:12 INFO]: [UserSuffix] | | | |___ ___ _ _/ __|_  _ / _|/ _(_)_ __
[19:09:12 INFO]: [UserSuffix] | |_| (_-</ -_) '_\__ \ || |  _|  _| \ \ /
[19:09:12 INFO]: [UserSuffix]  \___//__/\___|_| |___/\_,_|_| |_| |_/_\_\
[19:09:12 INFO]: [UserSuffix]  UserSuffix v1.3.1
[19:09:12 INFO]: [UserSuffix] UserSuffix 1.3.1 开始启动...
[19:09:12 INFO]: [UserSuffix] Loading plugin configurations...
[19:09:12 INFO]: [UserSuffix] Register handlers...
[19:09:12 ERROR]: Error occurred while enabling UserSuffix v1.3.1 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving interface method 'boolean cc.carm.lib.easysql.api.SQLTable.create(cc.carm.lib.easysql.api.SQLManager)' the class loader 'UserSuffix-1.3.1.jar' @648f3142 of the current class, com/artformgames/plugin/usersuffix/user/SuffixLoader, and the class loader 'QuickShop-Hikari-6.2.0.7.jar' @3e985be8 for the method's defining class, cc/carm/lib/easysql/api/SQLTable, have different Class objects for the type cc/carm/lib/easysql/api/SQLManager used in the signature (com.artformgames.plugin.usersuffix.user.SuffixLoader is in unnamed module of loader 'UserSuffix-1.3.1.jar' @648f3142, parent loader java.net.URLClassLoader @108c4c35; cc.carm.lib.easysql.api.SQLTable is in unnamed module of loader 'QuickShop-Hikari-6.2.0.7.jar' @3e985be8, parent loader java.net.URLClassLoader @108c4c35)
        at UserSuffix-1.3.1.jar/com.artformgames.plugin.usersuffix.user.SuffixLoader.<init>(SuffixLoader.java:27) ~[UserSuffix-1.3.1.jar:?]
        at UserSuffix-1.3.1.jar/com.artformgames.plugin.usersuffix.Main.initialize(Main.java:38) ~[UserSuffix-1.3.1.jar:?]
        at ArtCore-1.1.1.jar/cc.carm.lib.easyplugin.EasyPlugin.onEnable(EasyPlugin.java:71) ~[ArtCore-1.1.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:669) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:618) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:772) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:534) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:363) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1251) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:344) ~[purpur-1.21.3.jar:1.21.3-2358-16ce24a]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[19:09:12 INFO]: [UserSuffix] Disabling UserSuffix v1.3.1
[19:09:12 INFO]: [ArtCore] Unregistering all handlers from #UserSuffix ...
```
### **Environment**

- System: `Debian 12` 
- Java version: `Java 21 (OpenJDK 64-Bit Server VM 21.0.2+13-LTS; Eclipse Adoptium Temurin-21.0.2+13) on Linux 6.1.0-18-amd64 (amd64)`

**Comment by CarmJos** [comment]
目测是和 Quickshop-Hikari 撞了，可能是依赖处理问题，将在下个版本解决。

**Comment by CarmJos** [comment]
实际确定是QS那边的问题。

**Comment by CarmJos** [comment]
请提供一个 /qs paste 的链接。

**Comment by Sraconni** [comment]
> 请提供一个 /qs paste 的链接。

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2Fs4x2RW3iKY

**Comment by CarmJos** [comment]
该议题跟进 https://github.com/QuickShop-Community/QuickShop-Hikari/issues/1827 即可解决。
